
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;
	private global::Gtk.Button buttonAdd;
	private global::Gtk.Label labelOperation;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Label labelFirst;
	private global::Gtk.Label labelSecond;
	private global::Gtk.Label labelResult;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Entry entryFirst;
	private global::Gtk.Entry entrySecond;
	private global::Gtk.Entry entryResult;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Button buttonRst;
	private global::Gtk.Button buttonQuit;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Button buttonSub;
	private global::Gtk.Button buttonMul;
	private global::Gtk.Button buttonDiv;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Калькулятор");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.buttonAdd = new global::Gtk.Button ();
		this.buttonAdd.CanFocus = true;
		this.buttonAdd.Name = "buttonAdd";
		this.buttonAdd.UseUnderline = true;
		this.buttonAdd.BorderWidth = ((uint)(10));
		this.buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("Сложение");
		this.table1.Add (this.buttonAdd);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonAdd]));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table1.Gtk.Table+TableChild
		this.labelOperation = new global::Gtk.Label ();
		this.labelOperation.Name = "labelOperation";
		this.labelOperation.LabelProp = global::Mono.Unix.Catalog.GetString ("Выберите операцию");
		this.table1.Add (this.labelOperation);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelOperation]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Homogeneous = true;
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelFirst = new global::Gtk.Label ();
		this.labelFirst.Name = "labelFirst";
		this.labelFirst.LabelProp = global::Mono.Unix.Catalog.GetString ("Первое число");
		this.vbox1.Add (this.labelFirst);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelFirst]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelSecond = new global::Gtk.Label ();
		this.labelSecond.Name = "labelSecond";
		this.labelSecond.LabelProp = global::Mono.Unix.Catalog.GetString ("Второе число");
		this.vbox1.Add (this.labelSecond);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelSecond]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelResult = new global::Gtk.Label ();
		this.labelResult.Name = "labelResult";
		this.labelResult.LabelProp = global::Mono.Unix.Catalog.GetString ("Результат");
		this.vbox1.Add (this.labelResult);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelResult]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.table1.Add (this.vbox1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox1]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Homogeneous = true;
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryFirst = new global::Gtk.Entry ();
		this.entryFirst.CanFocus = true;
		this.entryFirst.Name = "entryFirst";
		this.entryFirst.IsEditable = true;
		this.entryFirst.InvisibleChar = '●';
		this.entryFirst.Xalign = 1F;
		this.vbox2.Add (this.entryFirst);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entryFirst]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entrySecond = new global::Gtk.Entry ();
		this.entrySecond.CanFocus = true;
		this.entrySecond.Name = "entrySecond";
		this.entrySecond.IsEditable = true;
		this.entrySecond.InvisibleChar = '●';
		this.entrySecond.Xalign = 1F;
		this.vbox2.Add (this.entrySecond);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entrySecond]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entryResult = new global::Gtk.Entry ();
		this.entryResult.CanFocus = true;
		this.entryResult.Name = "entryResult";
		this.entryResult.IsEditable = true;
		this.entryResult.InvisibleChar = '●';
		this.entryResult.Xalign = 1F;
		this.vbox2.Add (this.entryResult);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entryResult]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.table1.Add (this.vbox2);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox2]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = 6;
		this.vbox3.BorderWidth = ((uint)(10));
		// Container child vbox3.Gtk.Box+BoxChild
		this.buttonRst = new global::Gtk.Button ();
		this.buttonRst.CanFocus = true;
		this.buttonRst.Name = "buttonRst";
		this.buttonRst.UseUnderline = true;
		this.buttonRst.Label = global::Mono.Unix.Catalog.GetString ("Сброс");
		this.vbox3.Add (this.buttonRst);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonRst]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.buttonQuit = new global::Gtk.Button ();
		this.buttonQuit.CanFocus = true;
		this.buttonQuit.Name = "buttonQuit";
		this.buttonQuit.UseUnderline = true;
		this.buttonQuit.Label = global::Mono.Unix.Catalog.GetString ("Закрыть");
		this.vbox3.Add (this.buttonQuit);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonQuit]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.table1.Add (this.vbox3);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox3]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		this.vbox5.BorderWidth = ((uint)(10));
		// Container child vbox5.Gtk.Box+BoxChild
		this.buttonSub = new global::Gtk.Button ();
		this.buttonSub.CanFocus = true;
		this.buttonSub.Name = "buttonSub";
		this.buttonSub.UseUnderline = true;
		this.buttonSub.Label = global::Mono.Unix.Catalog.GetString ("Вычитание");
		this.vbox5.Add (this.buttonSub);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonSub]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.buttonMul = new global::Gtk.Button ();
		this.buttonMul.CanFocus = true;
		this.buttonMul.Name = "buttonMul";
		this.buttonMul.UseUnderline = true;
		this.buttonMul.Label = global::Mono.Unix.Catalog.GetString ("Умножение");
		this.vbox5.Add (this.buttonMul);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonMul]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.buttonDiv = new global::Gtk.Button ();
		this.buttonDiv.CanFocus = true;
		this.buttonDiv.Name = "buttonDiv";
		this.buttonDiv.UseUnderline = true;
		this.buttonDiv.Label = global::Mono.Unix.Catalog.GetString ("Деление");
		this.vbox5.Add (this.buttonDiv);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonDiv]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.table1.Add (this.vbox5);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox5]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(2));
		w17.RightAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 492;
		this.DefaultHeight = 405;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonSub.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.buttonMul.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.buttonDiv.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
		this.buttonRst.Clicked += new global::System.EventHandler (this.OnButtonRstClicked);
		this.buttonQuit.Clicked += new global::System.EventHandler (this.OnButtonQuitClicked);
		this.buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonOperationClicked);
	}
}
